### ISSUE TITLE
MiM Prevention Flaw

### ISSUE THREAD

**Issue by weijun-qiu** [Shawg/cpen442vpn#6]
I don't think our current mutual authentication is working. A man in the middle can just sit there and do nothing during the initial authentication process and step in during DH key exchange, which is not encrypted. In other words, Alice will authenticate with Bob but exchange key with Trudy. I think we have to either
1) do the authentication process with nonce after DH, and encrypt the process with the established keys, so that we can ensure we are authenticating the party that we established keys with.
2) don't do authentication with nonce, but instead we encrypt the DH communications with our initially shared keys, so that the man can't stand in the middle because he doesn't have the shared key.

Can I hear some opinions because I'm not so sure about these stuff to be honest.

**Comment by Shawg** [comment]
I think you're right, taking a look now

**Comment by Shawg** [comment]
I updated it so its in line with the examples in the text book
